In [14]:
import numpy as np 
import pandas as pd 
import plotly.express as px 
import plotly.graph_objects as go 
import plotly.offline as pyo
import plotly.figure_factory as ff
import dash 
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output,State
import json
import base64
import datetime as dt
import pandas_datareader.data as web

In [15]:
stock_name = pd.read_csv('../data/NASDAQcompanylist.csv', header= 0)

stock_name.head()

,Symbol,Name,LastSale,MarketCap,IPOyear,Sector,Industry
0,ABMD,"ABIOMED, Inc.",286.22,1.267320e+10,NaN,Health Care,Medical/Dental Instruments
1,ATVI,"Activision Blizzard, Inc",64.56,4.897726e+10,NaN,Technology,Computer Software: Prepackaged Software
2,ADBE,Adobe Systems Incorporated,218.61,1.076590e+11,1986.0,Technology,Computer Software: Prepackaged Software
3,AMD,"Advanced Micro Devices, Inc.",9.61,9.313356e+09,NaN,Technology,Semiconductors
4,AGNC,AGNC Investment Corp.,18.95,7.415454e+09,2008.0,Consumer Services,Real Estate Investment Trusts

In [ ]:
fp = dash.Dash()

fp.layout = html.Div([
    html.H1('Stock Ticker Dashboard', style= dict(color = 'blue')),
    html.Div([
        html.Div([
            html.H2('Select Stock Symbols:', style={'marginBottom': '0px','color': 'green'}),
            dcc.Dropdown(id = 'drop',
                         options= [{'label': stock_name.iloc[i,1],
                                   'value': stock_name.iloc[i,0]} for i in range(0,len(stock_name))],
                         style={'marginBottom': '10px'},
                         value =[],
                         multi= True)
        ], style= dict(width = '40%',border = '2px solid green',height = '100 px')),
        html.Div([
            html.Div([
            html.H2('Select Start and End dates:',style={'marginBottom': '0px', 'color': 'green'}),
            dcc.DatePickerRange(id = 'date_select',
                                start_date= dt.date(2022, 1, 1),
                                style= dict(marginBottom= '20px',width = '500px', height = '30px'))
            ])
        ], style= dict(width = '40%', display = 'inline-block',border = '2px solid red', height = '100 px')),
        html.Button(id = 'clt', 
                    children= 'Submit', 
                    n_clicks=0,
                    style= {'fontSize': '18px',
                            'padding': '10px 20px',
                            'height': '50px',
                            'width': '150px',
                            'margin': '10px'})
    ],style={
        'display': 'flex',
        'alignItems': 'flex-end',  # Align children to bottom
        'gap': '10px',
        'border': '1px solid gray'
    }),
    dcc.Graph(id = 'close'
    )
])

@fp.callback(Output(component_id= 'close', component_property= 'figure'),
             [Input(component_id= 'clt',component_property= 'n_clicks'),
              State(component_id= 'date_select', component_property= 'start_date'),
              State(component_id= 'date_select', component_property= 'end_date'),
              State(component_id= 'drop', component_property= 'value')],
              prevent_initial_call=True)
def plt(click, sd, ed, sk):
    # data = web.DataReader('AAPL', 'stooq', start=start_date, end=end_date)
    # dt_r = pd.date_range(start= sd, end= ed, freq = 'D')
    # final = {'date_se': [dt.date.strftime(i,'%Y-%m-%d') for i in dt_r]}
    # final = {'date_se': [i for i in np.arange(0,20,1)], 'nb': [j for j in np.arange(0,20,1)]}
    pt_d = []
    for k in sk:
        tp = web.DataReader(k, 'stooq', start=sd, end=ed)
        tp = tp.reset_index()
        pt_d.append(go.Scatter(x = tp.Date,
                       y = tp.Close,
                       mode = 'lines',
                       name= k))
    pt_l = go.Layout(title = 'hello world')

    return {'data': pt_d, 'layout': pt_l}
# fp.run()

:

In [8]:
date_r = pd.date_range(start='2023-01-01', end='2023-01-10',freq='D')
pd.DataFrame({'datttt': [dt.date.strftime(i, '%Y-%m-%d') for i in date_r], 'nb': [j for j in np.arange(0,date_r.shape[0],1)]})

       datttt  nb
0  2023-01-01   0
1  2023-01-02   1
2  2023-01-03   2
3  2023-01-04   3
4  2023-01-05   4
5  2023-01-06   5
6  2023-01-07   6
7  2023-01-08   7
8  2023-01-09   8
9  2023-01-10   9

In [ ]:
import dash
from dash import html

app = dash.Dash()

app.layout = html.Div([
    html.Div([
        html.Div("Top-aligned", style={
            'display': 'inline-block',
            'height': '100px',
            'backgroundColor': 'lightblue',
            'width': '100px',
        }),
        html.Div("Bottom-aligned", style={
            'display': 'inline-block',
            'height': '100px',
            'backgroundColor': 'lightgreen',
            'width': '100px',
            'alignSelf': 'flex-end'
        })
    ], style={
        'display': 'flex',
        'alignItems': 'flex-end',  # Align children to bottom
        'height': '150px',
        'border': '1px solid gray'
    })
])


app.run(debug=True)

In [ ]:
import dash
from dash import html

app = dash.Dash()

app.layout = html.Div([
    html.Div("Left Box", style={'display': 'inline-block', 'width': '48%', 'backgroundColor': 'lightblue', 'padding': '10px'}),
    html.Div("Right Box", style={'display': 'inline-block', 'width': '48%', 'backgroundColor': 'lightgreen', 'padding': '10px'})
])

# app.run(debug=True)

In [23]:
start_date1 = dt.datetime(2020, 1, 1)
end_date2 = dt.datetime(2023, 1, 1)

data = web.DataReader('AAPL', 'stooq', start=start_date1, end=end_date2)

print(data.head())

               Open     High      Low    Close    Volume
Date
2022-12-30  126.933  128.457  125.967  128.437  77929881
2022-12-29  126.519  128.981  126.262  128.120  76583912
2022-12-28  128.180  129.522  124.423  124.591  86431778
2022-12-27  129.869  129.899  127.240  128.536  69810179
2022-12-23  129.414  130.893  128.150  130.345  64556865

In [32]:
print(data.reset_index()[:10])

        Date     Open     High      Low    Close     Volume
0 2022-12-30  126.933  128.457  125.967  128.437   77929881
1 2022-12-29  126.519  128.981  126.262  128.120   76583912
2 2022-12-28  128.180  129.522  124.423  124.591   86431778
3 2022-12-27  129.869  129.899  127.240  128.536   69810179
4 2022-12-23  129.414  130.893  128.150  130.345   64556865
5 2022-12-22  132.808  133.013  128.802  130.709   78757289
6 2022-12-21  131.451  135.237  131.225  133.895   86927072
7 2022-12-20  129.879  131.718  128.397  130.779   78333125
8 2022-12-19  133.557  133.647  129.810  130.848   80518032
9 2022-12-16  135.113  136.068  132.194  132.965  162019034

In [31]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
date_range_tp = pd.date_range(start='2023-01-01', end='2023-01-10',freq='D')
print(date_range_tp.tolist())

[Timestamp('2023-01-01 00:00:00', freq='D'), Timestamp('2023-01-02 00:00:00', freq='D'), Timestamp('2023-01-03 00:00:00', freq='D'), Timestamp('2023-01-04 00:00:00', freq='D'), Timestamp('2023-01-05 00:00:00', freq='D'), Timestamp('2023-01-06 00:00:00', freq='D'), Timestamp('2023-01-07 00:00:00', freq='D'), Timestamp('2023-01-08 00:00:00', freq='D'), Timestamp('2023-01-09 00:00:00', freq='D'), Timestamp('2023-01-10 00:00:00', freq='D')]

In [ ]:
import yfinance as yf

df = yf.download('GOOG', start='2020-01-01', end='2023-01-01')
print(df.head())

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker           GOOG       GOOG       GOOG       GOOG      GOOG
Date
2020-01-02  68.046204  68.084520  66.761289  66.761289  28132000
2020-01-03  67.712280  68.301492  66.960045  67.075298  23728000
2020-01-06  69.381874  69.495829  67.181792  67.181792  34646000
2020-01-07  69.338585  69.818809  69.191280  69.567504  30054000
2020-01-08  69.884995  70.246282  69.214168  69.275872  30560000